version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  worker:
    build: .
    command: ./scripts/start_worker.sh
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - redis
  beat:
    build: .
    command: ./scripts/start_beat.sh
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - redis
  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - FLOWER_PORT=5555
    depends_on:
      - rabbitmq
